import { Course } from './course';

export const COURSES: Course[] = [
  { id: 1, courseNum: 'CHE 100', courseName: 'Chemical Engineering Concepts 1', term: '1A',
    review: 'What an interesting course. This was the first Chemical Engineering related course I took. In terms of course content I already forgot most of the concepts but I will always remember process flow and equilibrium. CHE 100 does not require heavy mathematical skills nor extensive knowledge of chemical knowledge. Instead it requires understanding mass balance, mol balance, and controlling inputs and outputs. In terms of teaching, the department decided to take a unique approach. Instead of one professor they had 2 professor (Professor Boxin Zhao and Professor Michael Tam). Prof Tam taught the first half of the course while Prof Zhao taught the tutorials. After the midterm, they switched. There were weekly tutorials and they were mandatory. In the first half of the tutorial, the Prof held a quick review session on the concepts taught in class and in the second half was the weekly quiz. In my personal opinion, the quizzes were a good reflection on the material taught in class and forced you to study in order to do well in them. This course also had a lab component that was held by a different professor (Professor Jeff Gostik). This was one of the worst labs I have ever taken. The labs were a mess and were very random. We started off learning how to use excel and write lab reports. It was in this course that I learned the importance of word automation, citation management, and figure/diagram creation. Although this was useful, it had little to no connection to Chemical Engineering which was very surprising for a first year chemical engineering core course. He then had us learn how to use AutoCad PID (A software for creating Piping instrumentation diagram. The task was to replicate the piping diagram for the liquid nitrogen tank system outside of E6) He wanted a PID diagram which none of us knew what they were and how to even create one. The funny thing is that Jeff Gostik doesn’t even know how to use the program, yet he expects first years to learn how to use the software and connect the pipes with the correct valves and other equipment in 1 week time. I know many students ditched the AutoCad software and just used Microsoft Paint to create them. We then moved onto learning very basic python which he struggled teaching as well. This lab was so disorganized and so random that I barely learned anything from it. I have heard from some first years currently that there is a new curriculum and it has improved a lot. I am hoping it is better for the future students.'},
  { id: 2, courseNum: 'CHE 102', courseName: 'Chemistry For Engineers', term: '1A',
    review: 'test'},
  { id: 3, courseNum: 'MATH 115', courseName: 'Linear Algebra For Engineering', term: '1A',
    review: 'test'},
  { id: 4, courseNum: 'MATH 116', courseName: 'Calculus 1 For Engineering', term: '1A',
    review: 'test'},
  { id: 5, courseNum: 'PHYS 115', courseName: 'Mechanics', term: '1A',
    review: 'test'},

  { id: 6, courseNum: 'ECE 106', courseName: 'Electricity And Magnetism', term: '1B',
    review: 'test'},
  { id: 7, courseNum: 'ECE 108', courseName: 'Discrete Mathematics And Logic 1', term: '1B',
    review: 'test'},
  { id: 8, courseNum: 'ECE 124', courseName: 'Digital Circuits And Systems', term: '1B',
    review: 'test'},
  { id: 9, courseNum: 'ECE 140', courseName: 'Linear Circuits', term: '1B',
    review: 'test'},
  { id: 10, courseNum: 'ECE 119', courseName: 'Calculus 2 For Engineering', term: '1B',
    review: 'test'},

  { id: 11, courseNum: 'ECE 204', courseName: 'Numerical Methods', term: '2A',
    review: 'test'},
  { id: 12, courseNum: 'ECE 205', courseName: 'Advanced Calculus 1 for Electrical and Computer Engineers', term: '2A',
    review: 'test'},
  { id: 13, courseNum: 'ECE 222', courseName: 'Digital Computers', term: '2A',
    review: 'test'},
  { id: 14, courseNum: 'ECE 240', courseName: 'Electronic Circuits 1', term: '2A',
    review: 'test'},
  { id: 15, courseNum: 'ECE 250', courseName: 'Algorithms And Data Structures', term: '2A',
    review: 'test'},
  { id: 16, courseNum: 'ECE 290', courseName: 'Engineering Profession, Ethics, And Law', term: '2A',
    review: 'test'},

  { id: 17, courseNum: 'ECE 207', courseName: 'Signals And Systems', term: '2B',
    review: 'test'},
  { id: 18, courseNum: 'ECE 208', courseName: 'Discrete Mathematics And Logic 2', term: '2B',
    review: 'test'},
  { id: 19, courseNum: 'ECE 224', courseName: 'Embedded Microprocessor Systems', term: '2B',
    review: 'test'},
  { id: 20, courseNum: 'ECE 252', courseName: 'Systems Programming And Concurrency', term: '2B',
    review: 'test'},
  { id: 21, courseNum: 'ECE 298', courseName: 'Instrumentation And Prototyping Laboratory', term: '2B',
    review: 'test'},
  { id: 22, courseNum: 'ECE 298', courseName: 'Classical Mythology', term: '2B',
    review: 'test'},

  { id: 23, courseNum: 'ECE 306', courseName: 'Probability Theory and Statistics', term: '3A',
    review: 'test'},
  { id: 24, courseNum: 'ECE 327', courseName: 'Digital Hardware Systems', term: '3A',
    review: 'test'},
  { id: 25, courseNum: 'ECE 351', courseName: 'Compilers', term: '3A',
    review: 'test'},
  { id: 26, courseNum: 'ECE 380', courseName: 'Analog Control Systems', term: '3A',
    review: 'test'},
  { id: 27, courseNum: 'ENVS 200', courseName: 'Field Ecology', term: '3A',
    review: 'test'},

  { id: 28, courseNum: 'PD 8', courseName: 'Intercultural Skills', term: '2A',
    review: 'test'},
  { id: 29, courseNum: 'PD 5', courseName: 'Project Management', term: '2B',
    review: 'test'},
];